### ISSUE TITLE
spaCy 3.4 load() gives an unexpected keyword argument 'enable'

### ISSUE THREAD

**Issue by eritain** [UCREL/pymusas-models#3]
```
import spacy
english_tagger_pipeline = spacy.load('en_dual_none_contextual')
``` 

dies like this:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/nathan/usas/lib/python3.8/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "/home/nathan/usas/lib/python3.8/site-packages/spacy/util.py", line 429, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "/home/nathan/usas/lib/python3.8/site-packages/spacy/util.py", line 465, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, enable=enable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "/home/nathan/usas/lib/python3.8/site-packages/en_dual_none_contextual/__init__.py", line 46, in load
    return load_model_from_init_py(__file__, **overrides)
TypeError: load_model_from_init_py() got an unexpected keyword argument 'enable'
```

The `enable` keyword is a recent addition to spaCy.load() -- merged into master 2022-06-17, first released in v3.4.0 2022-07-11 -- and en_dual_none_contextual v0.3.1 doesn't know what to do with it. This probably affects other Pymusas models too.

It's fixed just by going to the signature of `load_model_from_init_py` and bodging in `**kwargs` to soak up any unknown keywords. (Well, I mean, not in the installed copy inside my `site-packages` ...) I'd love to send a pull request, but your system for contributing to this repo is beyond my comprehension, so ... there you go.

**Comment by perayson** [comment]
Thanks for flagging this @eritain, I think this is the same as issue [#34](https://github.com/UCREL/pymusas/issues/34) for [pymusas](https://github.com/UCREL/pymusas) where @matthewcoole reported a fix which is to use v3.3.1 of spacy instead of v3.4.0.
